import type { JobSeeker, Employer } from './types';

export const mockSeekers: JobSeeker[] = [
  {
    id: 'seeker-1',
    name: '张伟',
    phone: '91234567',
    wechat: 'zhangwei88',
    industry: 'fnb',
    skills: ['cooking', 'food prep', 'kitchen management'],
    experience_years: 5,
    location_preference: 'central',
    expected_salary_min: 2500,
    expected_salary_max: 3500,
    availability: 'immediate',
    bio: '5年餐饮经验，擅长中餐烹饪',
    created_at: new Date().toISOString(),
  },
  {
    id: 'seeker-2',
    name: 'Maria Santos',
    phone: '81234567',
    industry: 'cleaning',
    skills: ['housekeeping', 'ironing', 'cooking'],
    experience_years: 3,
    location_preference: 'east',
    expected_salary_min: 1800,
    expected_salary_max: 2500,
    availability: 'oneWeek',
    created_at: new Date().toISOString(),
  },
  {
    id: 'seeker-3',
    name: '李明',
    phone: '98765432',
    wechat: 'liming_sg',
    industry: 'logistics',
    skills: ['driving', 'forklift', 'warehouse'],
    experience_years: 8,
    location_preference: 'west',
    expected_salary_min: 3000,
    expected_salary_max: 4000,
    availability: 'twoWeeks',
    bio: '持有3号驾照，有叉车证',
    created_at: new Date().toISOString(),
  },
  {
    id: 'seeker-4',
    name: 'Arun Kumar',
    phone: '87654321',
    industry: 'construction',
    skills: ['plumbing', 'electrical', 'tiling'],
    experience_years: 10,
    location_preference: 'any',
    expected_salary_min: 3500,
    expected_salary_max: 5000,
    availability: 'immediate',
    created_at: new Date().toISOString(),
  },
  {
    id: 'seeker-5',
    name: '王芳',
    phone: '92345678',
    wechat: 'wangfang_sg',
    industry: 'retail',
    skills: ['cashier', 'customer service', 'mandarin', 'english'],
    experience_years: 2,
    location_preference: 'central',
    expected_salary_min: 2000,
    expected_salary_max: 2800,
    availability: 'oneWeek',
    bio: '中英文流利，擅长客户服务',
    created_at: new Date().toISOString(),
  },
];

export const mockEmployers: Employer[] = [
  {
    id: 'employer-1',
    company_name: '金龙餐饮',
    contact_name: '陈老板',
    phone: '61234567',
    wechat: 'jinlong_boss',
    industry: 'fnb',
    job_title: '中餐厨师',
    job_description: '负责午晚餐中餐烹饪，需有至少3年经验',
    required_skills: ['cooking', 'food prep', 'chinese cuisine'],
    location: 'central',
    budget_min: 2800,
    budget_max: 3800,
    urgency: 'oneWeek',
    created_at: new Date().toISOString(),
  },
  {
    id: 'employer-2',
    company_name: 'CleanPro Services',
    contact_name: 'David Tan',
    phone: '62345678',
    industry: 'cleaning',
    job_title: 'Residential Cleaner',
    job_description: 'Part/full-time house cleaning in East area condos',
    required_skills: ['housekeeping', 'ironing'],
    location: 'east',
    budget_min: 1800,
    budget_max: 2600,
    urgency: 'immediate',
    created_at: new Date().toISOString(),
  },
  {
    id: 'employer-3',
    company_name: 'SwiftLog Pte Ltd',
    contact_name: 'Mike Wong',
    phone: '63456789',
    industry: 'logistics',
    job_title: 'Warehouse Operative & Driver',
    job_description: 'Warehouse operations and delivery driving in Jurong area',
    required_skills: ['driving', 'forklift', 'warehouse'],
    location: 'west',
    budget_min: 3200,
    budget_max: 4200,
    urgency: 'oneMonth',
    created_at: new Date().toISOString(),
  },
  {
    id: 'employer-4',
    company_name: '新城建筑',
    contact_name: '黄经理',
    phone: '64567890',
    wechat: 'xincheng_hr',
    industry: 'construction',
    job_title: '水电工',
    job_description: '住宅水电安装维修，需有相关证书',
    required_skills: ['plumbing', 'electrical'],
    location: 'any',
    budget_min: 3800,
    budget_max: 5500,
    urgency: 'immediate',
    created_at: new Date().toISOString(),
  },
  {
    id: 'employer-5',
    company_name: 'FashionMart',
    contact_name: 'Sarah Lee',
    phone: '65678901',
    industry: 'retail',
    job_title: 'Sales Associate',
    job_description: 'Retail sales at Orchard Rd store, bilingual preferred',
    required_skills: ['cashier', 'customer service', 'english'],
    location: 'central',
    budget_min: 2200,
    budget_max: 3000,
    urgency: 'oneWeek',
    created_at: new Date().toISOString(),
  },
];
